
### get tooele tech route
GET http://localhost:3000/ttech HTTP/1.1

### get the root path /
GET http://localhost:3000 HTTP/1.1

### get all students
GET http://localhost:3000/students HTTP/1.1

### get one student
GET http://localhost:3000/students/659dd64c75547b243bc3b49c HTTP/1.1

###create a student
 POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json 

{  
  "firstName": "Phil",
  "lastName": "Reaves",
  "email": "Browser@fear.com",
  "age": 42,
  "currentCollege": "Cool Tech"
}

### update a student
PATCH http://localhost:3000/students/659f1c3df166a9dd527e7857 HTTP/1.1
Content-Type: application/json

{  
  "firstName": "bill",
  "lastName": "fell",
  "email": "lol@wired.com",
  "age": 42,
  "currentCollege": "Wired Tech"
}

### delete a student
DELETE http://localhost:3000/students/659f19faa042d899fc322b05 HTTP/1.1

